STRINGS = GLOBAL.STRINGS

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_OFFENSE_UP_NESS_START = "I feel like I pack a punch!"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_OFFENSE_UP_NESS_END = "It was fun while it lasted."

STRINGS.CHARACTERS.GRAMNESS.ACTIONFAIL.USE_PSI.CANT_CAST_FRIEND = "It wouldn't be nice to target my friend like that!"
STRINGS.CHARACTERS.GRAMNESS.ACTIONFAIL.USE_PSI.NOT_ENOUGH_SANITY = "No can do!"
STRINGS.CHARACTERS.GRAMNESS_ACTIONFAIL.USE_PSI.SELF_HAS_BUFF = "I've already covered myself!"
STRINGS.CHARACTERS.GRAMNESS.ACTIONFAIL.USE_PSI.TARGET_HAS_BUFF = "I just gave them a helping hand!"
STRINGS.CHARACTERS.GRAMNESS.ACTIONFAIL.USE_PSI.ALREADY_TARGETTED = "I got them already!"