STRINGS = GLOBAL.STRINGS

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_OFFENSE_UP_NESS_START = "I feel like I pack a punch!"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_OFFENSE_UP_NESS_END = "It was fun while it lasted."